sudo docker pull gcr.io/spinnaker-marketplace/deck 
sudo docker pull gcr.io/spinnaker-marketplace/orca 
sudo docker pull gcr.io/spinnaker-marketplace/gate 
sudo docker pull gcr.io/spinnaker-marketplace/igor 
sudo docker pull gcr.io/spinnaker-marketplace/echo 
sudo docker pull gcr.io/spinnaker-marketplace/halyard 
sudo docker pull gcr.io/spinnaker-marketplace/clouddriver 
sudo docker pull gcr.io/spinnaker-marketplace/front50 
sudo docker pull gcr.io/spinnaker-marketplace/rosco 
sudo docker pull bitnami/redis 
sudo docker pull minio/minio 
