{
 "title": "StageInsights",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cdName", "label": "CD Name", "query": { "query": "label_values(sourceName)" } },
   { "name": "application", "label": "Application", "query": { "query": "label_values(appName)" } },
   { "name": "startTime", "label": "start time", "query": "1699900200000" },
   { "name": "endTime", "label": "end time", "query": "1700041559000" }
  ]
 },
 "panels": [
  {
   "title": "Failed Stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stages_execution_duration_counter_total{ status=\"TERMINAL\",appName=~\"$application\",sourceName=~\"$cdName\"} >= $startTime <= $endTime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Awaiting User Action",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((currently_executing_stages_ratio{stageType =~ \"manualJudgment|approval\",appName=~\"$application\",sourceName=~\"$cdName\"}) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stages_execution_duration_counter_total{ status=\"SKIPPED\",appName=~\"$application\",sourceName=~\"$cdName\"} >= $startTime <= $endTime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(stages_execution_duration_counter_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by(executionId, appName,pipelineName,stageName, duration, srcBaseUrl,stageType)(stages_execution_duration_counter_total{ status=\"TERMINAL\",appName=~\"$application\",sourceName=~\"$cdName\"} >= $startTime <= $endTime) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Skipped  stages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(executionId, appName,pipelineName,stageName, duration, srcBaseUrl)(stages_execution_duration_counter_total{ status=\"SKIPPED\",appName=~\"$application\",sourceName=~\"$cdName\"} >= $startTime <= $endTime )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Awaiting User Action",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(pipelineName, appName, stageName, stageType,sourceName, srcBaseUrl) (currently_executing_stages_ratio{stageType =~ \"manualJudgment|approval\",sourceName=~\"$cdName\",appName=~\"$application\"}) > 0"
    }
   ]
  }
 ]
}