sudo docker save gcr.io/spinnaker-marketplace/deck  -o /vagrant/docker_images/deck.tar
sudo docker save gcr.io/spinnaker-marketplace/orca  -o /vagrant/docker_images/orca.tar
sudo docker save gcr.io/spinnaker-marketplace/gate  -o /vagrant/docker_images/gate.tar
sudo docker save gcr.io/spinnaker-marketplace/igor  -o /vagrant/docker_images/igor.tar
sudo docker save gcr.io/spinnaker-marketplace/echo  -o /vagrant/docker_images/echo.tar
sudo docker save gcr.io/spinnaker-marketplace/halyard  -o /vagrant/docker_images/halyard.tar
sudo docker save gcr.io/spinnaker-marketplace/clouddriver  -o /vagrant/docker_images/clouddriver.tar
sudo docker save gcr.io/spinnaker-marketplace/front50  -o /vagrant/docker_images/front50.tar
sudo docker save gcr.io/spinnaker-marketplace/rosco  -o /vagrant/docker_images/rosco.tar
sudo docker save bitnami/redis  -o /vagrant/docker_images/redis.tar
sudo docker save minio/minio  -o /vagrant/docker_images/minio-new.tar
