{
 "title": "PipeInsights",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "numberOfBar", "label": "count", "query": "5,10,20" },
   {
    "name": "timeFilter",
    "label": "Time",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cdName", "label": "CD Name", "query": { "query": "label_values(sourceName)" } },
   { "name": "application", "label": "Application", "query": { "query": "label_values(appName)" } },
   { "name": "offsetDuration", "label": "offset", "query": "2h,3h,1d,1s" },
   { "name": "startTime", "label": "start time", "query": "1699936005163" },
   { "name": "endTime", "label": "end time", "query": "1699936305250" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Executions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status)(increase(pipelines_execution_count_counter_total{appName=~\"$application\",sourceName=~\"$cdName\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(new_pipelines_count_total{type=\"application\",appName=~\"$application\",sourceName=~\"$cdName\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Running Pipelines",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pipelineName,appName,stageName,sourceName,srcBaseUrl)(currently_executing_pipelines_new_ratio{appName=~\"$application\",sourceName=~\"$cdName\"}) > 0"
    }
   ]
  },
  {
   "title": "Slowest Pipelines",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "pipelines_execution_duration_counter_total{appName=~\"$application\",sourceName=~\"$cdName\"} >= $startTime <= $endTime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fastest Pipelines",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "pipelines_execution_duration_counter_total{appName=~\"$application\",sourceName=~\"$cdName\"}  >= $startTime <= $endTime ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Successful Pipelines",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,changes(pipelines_execution_count_counter_total{status=~\"SUCCEEDED\",appName=~\"$application\",sourceName=~\"$cdName\"}[$timeFilter] offset $offsetDuration) + 1)",
     "legendFormat": "{{appName}}  - {{pipelineName}} "
    }
   ]
  },
  {
   "title": "Most Failed Pipelines",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, changes(pipelines_execution_count_counter_total{status=~\"TERMINAL\",appName=~\"$application\",sourceName=~\"$cdName\"}[$timeFilter] offset $offsetDuration) + 1)",
     "legendFormat": "{{appName}}  - {{pipelineName}}"
    }
   ]
  }
 ]
}